### ISSUE TITLE
Answering call for new maintainers

### ISSUE THREAD

**Issue by joshuadavidthomas** [nicoddemus/pytest-rich#1]
Hiya!

Great minds think alike! I actually started something extremely similiar the past couple of days, [`joshuadavidthomas/pytest-rich-reporter`](https://github.com/joshuadavidthomas/pytest-rich-reporter), though my project is barely past the 'get the bare minimum working implementation` phase.

At my day job I'm a web developer using primarily Django, so I'm familiar with *using* pytest. However, I'm quite green when it comes to actually developing custom plugins for it. I started the project as a way to explore and learn a bit of the internals of pytest.

If you'd be willing, I'd love to come on and help out in whatever way I can.

**Comment by nicoddemus** [comment]
Hi @joshuadavidthomas!

Sounds great!

Feel free to look at the code and the issues I've opened up, and working in any of them. As things progress and you contribute more to the project, we can make you an official maintainer and even eventually transferring the repository to you if you like.

Closing this then, welcome!

**Comment by mazulo** [comment]
Hi @nicoddemus @joshuadavidthomas!

First thank you all for the work on this project. I've just stumbled upon a post that mentioned this project and I got very interested on contributing to it. When you get a chance please let me know how can I help

**Comment by nicoddemus** [comment]
Thanks @mazulo!

Feel free to browse the existing issues, and pick up any that interests you. Have you worked with pytest plugins before?

**Comment by mazulo** [comment]
> Thanks @mazulo!
> 
> 
> 
> Feel free to browse the existing issues, and pick up any that interests you. Have you worked with pytest plugins before?

Hey @nicoddemus not much. What I've done before was digging into the source code from a few plugins when I faced an issue and was trying to understand how it worked. But I'm going to take a look at the Pytest docs about plugins to get more familiarized/context
