### ISSUE TITLE
Allow for other plugins to add to report header

### ISSUE THREAD

**Issue by joshuadavidthomas** [nicoddemus/pytest-rich#10]
If you use another pytest plugin that adds additional info to the report header, e.g. `pytest-django` adds a line containing information about the Django app being tested, `pytest-rich` doesn't display this.

**Comment by nicoddemus** [comment]
We need to call [`pytest_report_header`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_report_header) in order to obtain that information. 👍

**Comment by joshuadavidthomas** [comment]
Relevant section in pytest default terminal reporter: 

https://github.com/pytest-dev/pytest/blob/50b232b0cb39490776da2658ae69c669ce263050/src/_pytest/terminal.py#L720-L722
