### ISSUE TITLE
Move project metadata to `setup.cfg`

### ISSUE THREAD

**Issue by joshuadavidthomas** [nicoddemus/pytest-rich#12]
Current [Python packaging docs](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata) recommend using `setup.cfg` unless you need to support dynamic metadata. 

I see nothing in the current `setup.py` that necessitates a need for dynamic metadata (maybe in the future? but not now). Though, I am not a seasoned Python packager so I am open to the fact I may be wrong about this.

**Comment by nicoddemus** [comment]
FTR we only use `setup.py` because that's what the CookieCutter pytest plugin gives us, so I don't see any problem in migrating to `setup.cfg`. We can use pytest's as basis too.

**Comment by fruch** [comment]
Why not go all the way to pyproject.toml ?

**Comment by nicoddemus** [comment]
As long we support editable installs, I'm OK with `pyproject.toml`. I don't recall the details, but there was an incompatibility with editable installs that prevented pytest itself from using `pyproject.toml` directly, however this might have changed recently.

**Comment by fruch** [comment]
> As long we support editable installs, I'm OK with `pyproject.toml`. I don't recall the details, but there was an incompatibility with editable installs that prevented pytest itself from using `pyproject.toml` directly, however this might have changed recently.

It was working for me with `poetry` (with version installed out of git), on it's last formal release `pip install -e .` doesn't work yet.
as `setuptools`, I need to check.
