### ISSUE TITLE
Use mypy in pre-commit

### ISSUE THREAD

**Issue by nicoddemus** [nicoddemus/pytest-rich#14]
Since we are using type annotations, I think we should enable mypy in the pre-commit configuration.

We might also consider configuring mypy to demand type annotations for all parameters and return types in `pytest_rich.py`, while also enabling full type checking even in non-annotated functions under `tests/`.

**Comment by joshuadavidthomas** [comment]
I have a branch for this, but will probably need a few cleanup PRs before merging it because there are quite a few type errors to work through. 

A couple in the `RichTerminalReporter`, but embarrisingly for me, most of them are in the custom traceback class I wrote. 😳

**Comment by nicoddemus** [comment]
Ahh that is absolutely normal, if no tool is checking it, it is easy to introduce erros!
