### ISSUE TITLE
Tweak GHA triggers for `test.yml` workflow

### ISSUE THREAD

**Issue by joshuadavidthomas** [nicoddemus/pytest-rich#24]
Currently when a PR is opened, the Test workflow is run twice for each job in the os/python version matrix, one for the push and one for the PR.

![image](https://user-images.githubusercontent.com/19896267/156391417-11067e3b-5b89-4d4f-870b-41fca2479bdc.png)

I wonder if there isn't a way to tweak the triggers to only run once, perhaps by removing the `pull_request` trigger?

**Comment by nicoddemus** [comment]
In pytest (and other plugins) we configure like this:

https://github.com/pytest-dev/pytest/blob/e466a87bb082ea5f7377f84038322e9bc8fba789/.github/workflows/main.yml#L3-L16

**Comment by joshuadavidthomas** [comment]
Actually, this is a non issue. Dug in a bit and realized it was running twice because I was pushing directly to branches on this repo instead of my own fork. (It's what I'm used to at my day job.)

I will switch to developing on my fork and submitting PRs from it.

**Comment by nicoddemus** [comment]
Yeah I always contribute from forks, even for repos I own: it is safer this way as there's no chance of an accidental commit to `main`, or polluting the main repo with feature branches. 👍
