### ISSUE TITLE
Show test summary of failed tests at the end

### ISSUE THREAD

**Issue by nicoddemus** [nicoddemus/pytest-rich#4]
When pytest is ran with `-a`, we show a nice one line-summary of failed tests. pytest-rich should support that too.

**Comment by bhavaniravi** [comment]
Hey @nicoddemus 

I'm working on a PR for this. Can you tell me a case where there will be multiple error messages?
https://github.com/bhavaniravi/pytest-rich/blob/0510d573f16876c80c0d3492b9e01fa36877cb35/pytest_rich.py#L476

Is it a good idea to persist these error messages at `RichExceptionChainRepr`? In that case, we have to continue the` tb` object to access them.

**Comment by nicoddemus** [comment]
> I'm working on a PR for this. Can you tell me a case where there will be multiple error messages?

**Comment by bhavaniravi** [comment]
I will work on this

**Comment by nicoddemus** [comment]
Thanks @bhavaniravi!

I think some good defaults would be:

* `-q`: no summary
* default: show failures/errors only 
* `-v`: show all (failures/errors/xfail/skips)

What do you think @joshuadavidthomas ?

**Comment by joshuadavidthomas** [comment]
👍 Yeah, those seem like sensible defaults!
